# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(542, 243)
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(0, 10, 531, 221))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.variety_name_input = QtWidgets.QLineEdit(self.widget)
        self.variety_name_input.setObjectName("variety_name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.variety_name_input)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.degree_of_roasting_input = QtWidgets.QLineEdit(self.widget)
        self.degree_of_roasting_input.setObjectName("degree_of_roasting_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.degree_of_roasting_input)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ground_bean_input = QtWidgets.QLineEdit(self.widget)
        self.ground_bean_input.setObjectName("ground_bean_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ground_bean_input)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.flavor_description_input = QtWidgets.QLineEdit(self.widget)
        self.flavor_description_input.setObjectName("flavor_description_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.flavor_description_input)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.price_input = QtWidgets.QLineEdit(self.widget)
        self.price_input.setObjectName("price_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price_input)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.package_volume_input = QtWidgets.QLineEdit(self.widget)
        self.package_volume_input.setObjectName("package_volume_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.package_volume_input)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.add_button = QtWidgets.QPushButton(self.splitter)
        self.add_button.setObjectName("add_button")
        self.edit_button = QtWidgets.QPushButton(self.splitter)
        self.edit_button.setEnabled(True)
        self.edit_button.setMinimumSize(QtCore.QSize(100, 0))
        self.edit_button.setObjectName("edit_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название сорта:"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки:"))
        self.label_3.setText(_translate("Dialog", "Молотый/в зернах:"))
        self.label_4.setText(_translate("Dialog", "Описание вкуса:"))
        self.label_5.setText(_translate("Dialog", "Цена:"))
        self.label_6.setText(_translate("Dialog", "Объем упаковки:"))
        self.add_button.setText(_translate("Dialog", "Добавить"))
        self.edit_button.setText(_translate("Dialog", "Редактировать"))
